=== 2martens/de.plugins-zum-selberbauen.ultimate/XSD/blockType.xsd
<?xml version="1.0"?>
<!-- This file is used for xml files which install, update or delete block types. -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.plugins-zum-selberbauen.de" targetNamespace="http://www.plugins-zum-selberbauen.de" elementFormDefault="qualified">
    <!-- include types -->
	<xs:include schemaLocation="types.xsd" />
    
    <!-- data node -->
    <xs:element name="data">
        <xs:complexType>
            <xs:all>
                <xs:element name="import" type="import" minOccurs="0" />
                <xs:element name="delete" type="delete" minOccurs="0" />
            </xs:all>
        </xs:complexType>
    </xs:element>
    
    <!-- import element type -->
    <xs:complexType name="import">
        <xs:sequence>
            <xs:element name="blocktype" type="blocktype" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    
    <!-- delete element type -->
    <xs:complexType name="delete">
        <xs:sequence>
            <xs:element name="blocktype" type="blocktype" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
        
    <!-- block type element type -->
    <xs:complexType name="blocktype">
        <xs:all>
            <xs:element name="blocktypeclassname" minOccurs="1" maxOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="27" />
                        <xs:maxLength value="80" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="blocktypename" minOccurs="1" maxOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1" />
                        <xs:maxLength value="80" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="fixedHeight" minOccurs="0" maxOccurs="1" type="pzs_boolean" />
        </xs:all>
    </xs:complexType>
</xs:schema>

=== 2martens/de.plugins-zum-selberbauen.ultimate/de.plugins-zum-selberbauen.ultimate/blockType.xml
<?xml version="1.0" encoding="UTF-8"?>
<data xmlns="http://www.plugins-zum-selberbauen.de" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.plugins-zum-selberbauen.de http://www.plugins-zum-selberbauen.de/XSD/blockType.xsd">
	<import>
		<blocktype>
			<blocktypeclassname><![CDATA[ultimate\system\blocktype\ContentBlockType]]></blocktypeclassname>
			<blocktypename><![CDATA[ultimate.blocktype.content]]></blocktypename>
			<fixedHeight>0</fixedHeight>
		</blocktype>
		<blocktype>
			<blocktypeclassname><![CDATA[ultimate\system\blocktype\MediaBlockType]]></blocktypeclassname>
			<blocktypename><![CDATA[ultimate.blocktype.media]]></blocktypename>
			<fixedHeight>1</fixedHeight>
		</blocktype>
	</import>
</data>
